### PR TITLE
Added facebook login feature

### PR DESCRIPTION
**Pull request by DikshantK2004**
Issue: #129 

- Implemented facebook login
- User gets redirected to mainActivity if already logged In or does login now
- Similar thing done on login page
[Screencast from 2023-12-24 16-13-24.webm](https://github.com/opencodeiiita/Text-It/assets/131744004/bf5e52cb-5b3d-4a82-843c-f525a6022d62)

### CODE REVIEW

**Comment by muffinboy19** [comment]
Can you upload a video of its working as

**Comment by DikshantK2004** [comment]
As?

**Comment by muffinboy19** [comment]
Like screen record and try to login using Facebook

**Comment by DikshantK2004** [comment]
Didn't I share the screen recording already?

**Pull request merged**
