### PR TITLE
Changed color in Navbar

### PR DESCRIPTION
**Pull request by Apoorv012**
Issue: #143

### CODE REVIEW

**Comment by Apoorv012** [comment]
The conflict is in baseHomeActivity, I did not make any significant changes in `baseHomeActivity.kt`. You can overwrite my changes in `baseHomeActivity.kt`

**Comment by muffinboy19** [comment]
okay i would do that pls attach the photo of the bottom nav bar too @Apoorv012

**Comment by Apoorv012** [comment]
Screenshot:
image

**Comment by muffinboy19** [comment]
Hey @Apoorv012 pls remove the background colour which comes when we select the icon

Screenshot_2023-12-27-01-56-06-04_8ee8015dd2b473d44c46c2d8d6942cec

**Comment by muffinboy19** [comment]
Also change the icons to one which have borders instead of filled svg icons, you can visit svgrepo for this task

**Comment by Apoorv012** [comment]
@muffinboy19 Please review.

Screenshot:
image

**Pull request merged**
